service: empresa-adhesion-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DB_USER: ${env:DB_USER}
    DB_HOST: ${env:DB_HOST}
    DB_NAME: ${env:DB_NAME}
    DB_PASS: ${env:DB_PASS}
    DB_PORT: ${env:DB_PORT}

functions:
  adhesion:
    handler: handler.handler
    events:
      - http:
          path: adhesion
          method: post
          cors: true

plugins:
  - serverless-offline
